DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS role;

CREATE TABLE user(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    is_admin INTEGER DEFAULT 0,
    is_confirmed INTEGER DEFAULT 0,

    nick_name TEXT DEFAULT "anonymous",
    about TEXT DEFAULT NULL,
    join_date DATE DEFAULT CURRENT_DATE,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    body TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    author_id INTEGER NOT NULL,
    FOREIGN KEY (author_id) REFERENCES user (id)
);

